<UserControl x:Class="RevitDBExplorer.UIComponents.CommandAndControl.CommandAndControlView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:RevitDBExplorer.UIComponents.CommandAndControl"
             xmlns:ap="clr-namespace:RevitDBExplorer.WPF.AttachedProperties"    
             mc:Ignorable="d" 
             d:DesignHeight="450" d:DesignWidth="800">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="auto"/>
            <RowDefinition Height="1*"/>
            <RowDefinition Height="auto"/>
        </Grid.RowDefinitions>
        <StackPanel Grid.Row="0">
            <TextBlock Text="selected Autodesk.Revit.DB.Element count:" > </TextBlock>
            <TextBlock Text="{Binding ItemsCount}" />
        </StackPanel>

        <DataGrid Grid.Row="1" AutoGenerateColumns="False" ItemsSource="{Binding Rows}"  ap:DataGridAP.BindableColumns="{Binding Columns}">
            <DataGrid.ColumnHeaderStyle>
                <Style TargetType="{x:Type DataGridColumnHeader}">
                    <Setter Property="LayoutTransform">
                        <Setter.Value>
                            <RotateTransform Angle="270" />
                        </Setter.Value>
                    </Setter>
                </Style>
            </DataGrid.ColumnHeaderStyle>

        </DataGrid>
        
    </Grid>
</UserControl>
